name: roqqu_mobile_t
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.10+1
  rive: ^0.13.4 
  riverpod_annotation: ^3.0.3
  go_router: ^14.1.1 
  fl_chart: ^0.68.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0




flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # It tells Flutter to include all files in these directories.
  assets:
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

  fonts:
  - family: Encode Sans
    fonts:
      - asset: fonts/EncodeSans-VariableFont_wdth,wght.ttf
  
  - family: Inter
    fonts:
      - asset: fonts/Inter-VariableFont_opsz,wght.ttf
      - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
